In [2]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import datetime
from scipy import stats
import os

It should have a dropdown menu to show the columns, and several types of graphs to show the data available and the gaps, as well as descriptive statistics for the metadata and the SDG dataset.  The analysis should be for each SDG, GICS Sector, Country, and the relationship between them via heatmaps and other visualizations.

In [57]:
path = "../Data/withFIGI.csv"
df_metadata = pd.read_csv(path, low_memory=False)

df_metadata

,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD,previousCloseDate-EOD,country-Inv,...,longName-FIGI,symbol-FIGI,figi,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI
0,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02,united states,...,2U INC,TWOU,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock
1,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03,united kingdom,...,88 ENERGY LTD,POQ,BBG000BWTTK9,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock
2,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2064.000,2022-08-03,japan,...,BIRDMAN INC,7063,BBG00NG9S234,BBG00NG9S234,BBG00NG9S261,JP,Equity,7063,Common Stock,Common Stock
3,2018,Hong Kong,HKD,HK,KYG2953R1149,AAC Technologies Holdings Inc,Common Stock,14.580,2022-08-03,hong kong,...,AAC TECHNOLOGIES HOLDINGS IN,A2XN,BBG000C162Q4,BBG000C162Q4,BBG001SKMWN2,GR,Equity,A2XN,Common Stock,Common Stock
4,2686,Hong Kong,HKD,HK,KYG000371040,AAG Energy Holdings Ltd,Common Stock,1.410,2022-08-03,hong kong,...,AAG ENERGY HOLDINGS LTD,2686,BBG009CXGZ63,BBG009CXGZ45,BBG009CXGZ54,HK,Equity,2686,Common Stock,Common Stock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17506,NaN,NaN,NaN,NaN,US98979J1097,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17507,NaN,NaN,NaN,NaN,CA98977K1084,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17508,NaN,NaN,NaN,NaN,CA98977R1038,NaN,NaN,NaN,NaN,NaN,...,ZOOMMED INC,ZMD/H,BBG000BYKYT4,BBG000BYKYT4,BBG001SJS399,CN,Equity,ZMD/H,Common Stock,Common Stock
17509,NaN,NaN,NaN,NaN,GB00BMHTHT14,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17510,NaN,NaN,NaN,NaN,US98986T1088,NaN,NaN,NaN,NaN,NaN,...,ZYNGA INC - CL A,ZNGAEUR,BBG005YZL376,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock

In [58]:
path = "../Data/LIst of 19.7 Stocks with FIGI if available - By Evelyn.xlsx"
df_197 = pd.read_excel(path, index_col=0)

df_197

,symbol_x,longName,Exchange,Country,country,name,full_name,isin,currency_x,currency_y,...,Country_Final,Code,figi,compositeFIGI,shareClassFIGI,exchCode,marketSector,securityDescription,securityType,securityType2
0,1ST,1ST GROUP LTD,ASX,Australia,australia,NaN,NaN,NaN,NaN,AUD,...,Australia,1.0,BBG008HNLRF4,BBG008HNLRF4,BBG008HNLRG3,AU,Equity,1ST,Common Stock,Common Stock
1,TWOU,2U INC,NASDAQ,United States of America,united states of america,NaN,NaN,NaN,NaN,USD,...,United States of America,1.0,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock
2,DDDX,3DX INDUSTRIES INC,PINK,United States of America,united states of america,NaN,NaN,NaN,NaN,USD,...,United States of America,1.0,BBG000C129N6,BBG000C129N6,BBG001STRH79,US,Equity,DDDX,Common Stock,Common Stock
3,MMM,3M CO,US Exchange,Mexico,mexico,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,88E,88 ENERGY LTD,LSE,United Kingdom,united kingdom,88 Energy Ltd,88 Energy Ltd,AU00000088E2,GBP,GBP,...,United Kingdom,1.0,BBG000C4PMQ3,BBG000C4PMQ3,BBG001SCV1F7,AU,Equity,88E,Common Stock,Common Stock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19731,ZYNE,ZYNERBA PHARMACEUTICALS INC,NASDAQ,United States of America,united states of america,NaN,NaN,NaN,NaN,USD,...,United States of America,1.0,BBG007BBS8B7,BBG007BBS8B7,BBG007BBS8C6,US,Equity,ZYNE,Common Stock,Common Stock
19732,ZYXI,ZYNEX INC,NASDAQ,United States of America,united states of america,NaN,NaN,NaN,NaN,USD,...,United States of America,1.0,BBG000BJBXZ2,BBG000BJBXZ2,BBG001S7T7V0,US,Equity,ZYXI,Common Stock,Common Stock
19733,ZNGA,ZYNGA INC - CL A,NASDAQ,Switzerland,switzerland,NaN,NaN,NaN,NaN,USD,...,United States of America,1.0,BBG000VD6768,BBG000VD6768,BBG001T24RN2,US,Equity,ZNGA,Common Stock,Common Stock
19734,ZYT,ZYTRONIC PLC,LSE,United Kingdom,united kingdom,NaN,NaN,NaN,NaN,GBP,...,United Kingdom,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19735,8295,ZZ CAPITAL INTERNATIONAL LTD,SEHK,Hong Kong,hong kong,ZZ Capital International Ltd,ZZ Capital International Ltd,KYG9895T1085,HKD,HKD,...,Hong Kong,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
df_197 = df_197.rename(columns = {'longName':'Name_197'})
df_metadata = df_metadata[df_metadata['Name_197'].notna()]
df_metadata = pd.merge(df_197['Name_197'], df_metadata, how='outer', on='Name_197').drop_duplicates(subset=['Name_197'])

df_metadata

,Name_197,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD,previousCloseDate-EOD,...,longName-FIGI,symbol-FIGI,figi,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI
0,1ST GROUP LTD,1ST,Australia,AUD,AU,AU0000001ST0,1stAvailable Ltd,Common Stock,0.010,2022-08-03,...,1ST GROUP LTD,1ST,BBG008HNLRF4,BBG008HNLRF4,BBG008HNLRG3,AU,Equity,1ST,Common Stock,Common Stock
1,2U INC,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02,...,2U INC,TWOU,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock
2,3DX INDUSTRIES INC,DDDX,USA,USD,US,US88556A1007,3Dx Industries Inc,Common Stock,0.060,2022-08-02,...,3DX INDUSTRIES INC,DDDX,BBG000C129N6,BBG000C129N6,BBG001STRH79,US,Equity,DDDX,Common Stock,Common Stock
3,3M CO,MMM,USA,USD,US,US88579Y1010,3M Company,Common Stock,141.750,2022-08-02,...,3M CO,MMM,BBG000BP52R2,BBG000BP52R2,BBG001S5T7X2,US,Equity,MMM,Common Stock,Common Stock
4,88 ENERGY LTD,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03,...,88 ENERGY LTD,POQ,BBG000BWTTK9,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20293,ZYNERBA PHARMACEUTICALS INC,ZYNE,USA,USD,US,US98986X1090,Zynerba Pharmaceuticals Inc,Common Stock,1.170,2022-08-03,...,ZYNERBA PHARMACEUTICALS INC,ZYNE,BBG007BBS8B7,BBG007BBS8B7,BBG007BBS8C6,US,Equity,ZYNE,Common Stock,Common Stock
20294,ZYNEX INC,ZYXI,USA,USD,US,US98986M1036,Zynex Inc,Common Stock,8.400,2022-08-03,...,ZYNEX INC,ZYXI,BBG000BJBXZ2,BBG000BJBXZ2,BBG001S7T7V0,US,Equity,ZYXI,Common Stock,Common Stock
20295,ZYNGA INC - CL A,NaN,NaN,NaN,NaN,US98986T1088,NaN,NaN,NaN,NaN,...,ZYNGA INC - CL A,ZNGAEUR,BBG005YZL376,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock
20296,ZYTRONIC PLC,ZYT,UK,GBX,LSE,GB0006971013,Zytronic,Common Stock,140.000,2022-08-03,...,ZYTRONIC PLC,ZYT,BBG000BZPV76,BBG000BZPTJ8,BBG001SFLP13,LN,Equity,ZYT,Common Stock,Common Stock
20297,ZZ CAPITAL INTERNATIONAL LTD,NaN,NaN,NaN,NaN,KYG9895T1085,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
df_eod = df_metadata.iloc[:, 1:9].dropna()

df_eod

,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD
0,1ST,Australia,AUD,AU,AU0000001ST0,1stAvailable Ltd,Common Stock,0.010
1,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200
2,DDDX,USA,USD,US,US88556A1007,3Dx Industries Inc,Common Stock,0.060
3,MMM,USA,USD,US,US88579Y1010,3M Company,Common Stock,141.750
4,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625
...,...,...,...,...,...,...,...,...
20291,ZYDUSWELL,India,INR,NSE,INE768C01010,Zydus Wellness Limited,Common Stock,1579.700
20292,ZYME,USA,USD,US,CA98985W1023,Zymeworks Inc,Common Stock,6.260
20293,ZYNE,USA,USD,US,US98986X1090,Zynerba Pharmaceuticals Inc,Common Stock,1.170
20294,ZYXI,USA,USD,US,US98986M1036,Zynex Inc,Common Stock,8.400
20296,ZYT,UK,GBX,LSE,GB0006971013,Zytronic,Common Stock,140.000

In [62]:
df_inv = df_metadata.iloc[:, 10:15]
df_inv['ISIN'] = df_metadata['ISIN']
df_inv.dropna(inplace = True)

df_inv

,country-Inv,name-Inv,full_name-Inv,currency-Inv,symbol-Inv,ISIN
1,united states,2U Inc,2U Inc,USD,TWOU,US90214J1016
4,united kingdom,88 Energy,88 Energy Ltd,GBP,88E,AU00000088E2
6,japan,A Dot,A Dot Co Ltd,JPY,7063,JP3160590000
13,hong kong,AAC Technologies,AAC Technologies Holdings Inc,HKD,2018,KYG2953R1149
14,hong kong,AAG Energy Holdings Ltd,AAG Energy Holdings Ltd,HKD,2686,KYG000371040
...,...,...,...,...,...,...
20281,united states,Zumiez,Zumiez Inc,USD,ZUMZ,US9898171015
20286,switzerland,Zurich Insurance Group,Zurich Insurance Group AG,CHF,ZURN,CH0011075394
20288,japan,ZUU,ZUU Co Ltd,JPY,4387,JP3411810009
20290,australia,Zyber Holdings,Zyber Holdings Ltd,AUD,ZYB,AU000000ZYB8
20297,hong kong,ZZ Capital Intl,ZZ Capital International Ltd,HKD,8295,KYG9895T1085

In [63]:
df_ib = df_metadata.iloc[:, 16:23]
df_ib['ISIN'] = df_metadata['ISIN']
df_ib.dropna(inplace = True)

df_ib

,industry-IB,longName-IB,marketName-IB,Symbol-IB,Country-IB,Exchange-IB,Currency-IB,ISIN
0,Communications,1ST GROUP LTD,1ST,1ST,Australia,ASX,AUD,AU0000001ST0
4,Energy,88 ENERGY LTD,88E,88E,United Kingdom,LSE,GBP,AU00000088E2
8,Industrial,A TOUTE VITESSE-ATV,MLATV,MLATV,France,SBF,EUR,FR0010050773
14,Energy,AAG ENERGY HOLDINGS LTD,2686,2686,Hong Kong,SEHK,HKD,KYG000371040
17,Industrial,AARON INDUSTRIES LTD,AARON,AARON,India,NSE,INR,INE721Z01010
...,...,...,...,...,...,...,...,...
20288,Communications,ZUU CO LTD,4387,4387,Japan,TSEJ,JPY,JP3411810009
20289,"Consumer, Non-cyclical",ZWACK UNICUM RT,ZWACK,ZWACK,Hungary,BUX,HUF,HU0000074844
20290,Technology,ZYBER HOLDINGS LTD,ZYB,ZYB,Australia,ASX,AUD,AU000000ZYB8
20291,"Consumer, Non-cyclical",ZYDUS WELLNESS LTD,ZYDUSWELL,ZYDUSWELL,India,NSE,INR,INE768C01010
20296,Industrial,ZYTRONIC PLC,ASQ1,ZYT,United Kingdom,LSE,GBP,GB0006971013

In [64]:
df_figi = df_metadata.iloc[:, 24:]
df_figi['ISIN'] = df_metadata['ISIN']
df_figi.dropna(inplace = True)

df_figi

,symbol-FIGI,figi,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI,ISIN
0,1ST,BBG008HNLRF4,BBG008HNLRF4,BBG008HNLRG3,AU,Equity,1ST,Common Stock,Common Stock,AU0000001ST0
1,TWOU,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock,US90214J1016
2,DDDX,BBG000C129N6,BBG000C129N6,BBG001STRH79,US,Equity,DDDX,Common Stock,Common Stock,US88556A1007
3,MMM,BBG000BP52R2,BBG000BP52R2,BBG001S5T7X2,US,Equity,MMM,Common Stock,Common Stock,US88579Y1010
4,POQ,BBG000BWTTK9,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock,AU00000088E2
...,...,...,...,...,...,...,...,...,...,...
20292,ZYME,BBG00GD15LJ5,BBG00GD15LJ5,BBG00247P1W0,US,Equity,ZYME,Common Stock,Common Stock,CA98985W1023
20293,ZYNE,BBG007BBS8B7,BBG007BBS8B7,BBG007BBS8C6,US,Equity,ZYNE,Common Stock,Common Stock,US98986X1090
20294,ZYXI,BBG000BJBXZ2,BBG000BJBXZ2,BBG001S7T7V0,US,Equity,ZYXI,Common Stock,Common Stock,US98986M1036
20295,ZNGAEUR,BBG005YZL376,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock,US98986T1088
20296,ZYT,BBG000BZPV76,BBG000BZPTJ8,BBG001SFLP13,LN,Equity,ZYT,Common Stock,Common Stock,GB0006971013