In [1]:
import numpy as np  
import pandas as pd

In [6]:
path = "./Data/withFIGI.csv"

df = pd.read_csv(path, index_col=0)  
df

,Name_197,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD,previousCloseDate-EOD,...,figi,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI,Not_Match,Source_Available
0,1ST GROUP LTD,1ST,Australia,AUD,AU,AU0000001ST0,1stAvailable Ltd,Common Stock,0.010,2022-08-03,...,BBG008HNLRF4,BBG008HNLRF4,BBG008HNLRG3,AU,Equity,1ST,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
1,2U INC,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02,...,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock,NaN,FIGI;Inv;IB;EOD;
2,3DX INDUSTRIES INC,DDDX,USA,USD,US,US88556A1007,3Dx Industries Inc,Common Stock,0.060,2022-08-02,...,BBG000C129N6,BBG000C129N6,BBG001STRH79,US,Equity,DDDX,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
3,3M CO,MMM,USA,USD,US,US88579Y1010,3M Company,Common Stock,141.750,2022-08-02,...,BBG000BP52R2,BBG000BP52R2,BBG001S5T7X2,US,Equity,MMM,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
4,88 ENERGY LTD,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03,...,BBG000BWTTK9,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock,NaN,FIGI;Inv;IB;EOD;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19731,ZYNERBA PHARMACEUTICALS INC,ZYNE,USA,USD,US,US98986X1090,Zynerba Pharmaceuticals Inc,Common Stock,1.170,2022-08-03,...,BBG007BBS8B7,BBG007BBS8B7,BBG007BBS8C6,US,Equity,ZYNE,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
19732,ZYNEX INC,ZYXI,USA,USD,US,US98986M1036,Zynex Inc,Common Stock,8.400,2022-08-03,...,BBG000BJBXZ2,BBG000BJBXZ2,BBG001S7T7V0,US,Equity,ZYXI,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
19733,ZYNGA INC - CL A,NaN,NaN,NaN,NaN,US98986T1088,NaN,NaN,NaN,NaN,...,BBG005YZL376,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock,NaN,FIGI;IB;
19734,ZYTRONIC PLC,ZYT,UK,GBX,LSE,GB0006971013,Zytronic,Common Stock,140.000,2022-08-03,...,BBG000BZPV76,BBG000BZPTJ8,BBG001SFLP13,LN,Equity,ZYT,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
19735,ZZ CAPITAL INTERNATIONAL LTD,NaN,NaN,NaN,NaN,KYG9895T1085,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Inv;

In [7]:
df = df.drop(['Not_Match', 'Source_Available'], axis=1)

df

,Name_197,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD,previousCloseDate-EOD,...,longName-FIGI,symbol-FIGI,figi,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI
0,1ST GROUP LTD,1ST,Australia,AUD,AU,AU0000001ST0,1stAvailable Ltd,Common Stock,0.010,2022-08-03,...,1ST GROUP LTD,1ST,BBG008HNLRF4,BBG008HNLRF4,BBG008HNLRG3,AU,Equity,1ST,Common Stock,Common Stock
1,2U INC,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02,...,2U INC,TWOU,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock
2,3DX INDUSTRIES INC,DDDX,USA,USD,US,US88556A1007,3Dx Industries Inc,Common Stock,0.060,2022-08-02,...,3DX INDUSTRIES INC,DDDX,BBG000C129N6,BBG000C129N6,BBG001STRH79,US,Equity,DDDX,Common Stock,Common Stock
3,3M CO,MMM,USA,USD,US,US88579Y1010,3M Company,Common Stock,141.750,2022-08-02,...,3M CO,MMM,BBG000BP52R2,BBG000BP52R2,BBG001S5T7X2,US,Equity,MMM,Common Stock,Common Stock
4,88 ENERGY LTD,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03,...,88 ENERGY LTD,POQ,BBG000BWTTK9,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19731,ZYNERBA PHARMACEUTICALS INC,ZYNE,USA,USD,US,US98986X1090,Zynerba Pharmaceuticals Inc,Common Stock,1.170,2022-08-03,...,ZYNERBA PHARMACEUTICALS INC,ZYNE,BBG007BBS8B7,BBG007BBS8B7,BBG007BBS8C6,US,Equity,ZYNE,Common Stock,Common Stock
19732,ZYNEX INC,ZYXI,USA,USD,US,US98986M1036,Zynex Inc,Common Stock,8.400,2022-08-03,...,ZYNEX INC,ZYXI,BBG000BJBXZ2,BBG000BJBXZ2,BBG001S7T7V0,US,Equity,ZYXI,Common Stock,Common Stock
19733,ZYNGA INC - CL A,NaN,NaN,NaN,NaN,US98986T1088,NaN,NaN,NaN,NaN,...,ZYNGA INC - CL A,ZNGAEUR,BBG005YZL376,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock
19734,ZYTRONIC PLC,ZYT,UK,GBX,LSE,GB0006971013,Zytronic,Common Stock,140.000,2022-08-03,...,ZYTRONIC PLC,ZYT,BBG000BZPV76,BBG000BZPTJ8,BBG001SFLP13,LN,Equity,ZYT,Common Stock,Common Stock
19735,ZZ CAPITAL INTERNATIONAL LTD,NaN,NaN,NaN,NaN,KYG9895T1085,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Country, Sector/Industry, Exchange, ISIN, FIGI

In [10]:
df_ck = df.copy()
df_ck['Ranking'] = 0

df_ck.loc[~df_ck['Country-EOD'].isnull(),'Ranking'] = 1 + df_ck['Ranking'].astype(int)
df_ck.loc[~df_ck['Exchange-EOD'].isnull(),'Ranking'] = 1 + df_ck['Ranking'].astype(int)
df_ck.loc[~df_ck['ISIN'].isnull(),'Ranking'] = 1 + df_ck['Ranking'].astype(int)
df_ck.loc[~df_ck['country-Inv'].isnull(),'Ranking'] = 1 + df_ck['Ranking'].astype(int)
df_ck.loc[~df_ck['Country-IB'].isnull(),'Ranking'] = 1 + df_ck['Ranking'].astype(int)
df_ck.loc[~df_ck['Exchange-IB'].isnull(),'Ranking'] = 1 + df_ck['Ranking'].astype(int)
df_ck.loc[~df_ck['figi'].isnull(),'Ranking'] = 1 + df_ck['Ranking'].astype(int)
df_ck.loc[~df_ck['exchCode-FIGI'].isnull(),'Ranking'] = 1 + df_ck['Ranking'].astype(int)

df_ck[['Name_197','Ranking']]

                           Name_197  Ranking
0                     1ST GROUP LTD        7
1                            2U INC        6
2                3DX INDUSTRIES INC        5
3                             3M CO        5
4                     88 ENERGY LTD        8
...                             ...      ...
19731   ZYNERBA PHARMACEUTICALS INC        5
19732                     ZYNEX INC        5
19733              ZYNGA INC - CL A        3
19734                  ZYTRONIC PLC        7
19735  ZZ CAPITAL INTERNATIONAL LTD        2

[19565 rows x 2 columns]

In [13]:
df_ck['Ranking'].value_counts().to_frame()

   Ranking
5     4301
7     3606
8     3111
6     2396
0     2129
1     1747
3     1643
4      507
2      125