In [1]:
import numpy as np
import pandas as pd
import requests

In [2]:
path = "./Data/metaData_IB_Inv.csv"

df_isin = pd.read_csv(path)  
df_isin

,country-Inv,name-Inv,full_name-Inv,currency-Inv,symbol-Inv,asset_class-Inv,ISIN,Name_197,industry-IB,longName-IB,marketName-IB,Symbol-IB,Country-IB,Exchange-IB,Currency-IB
0,united states,2U Inc,2U Inc,USD,TWOU,equity,US90214J1016,2U INC,"Consumer, Non-cyclical",2U INC,NMS,TWOU,NaN,NaN,NaN
1,united kingdom,88 Energy,88 Energy Ltd,GBP,88E,equity,AU00000088E2,88 ENERGY LTD,Energy,88 ENERGY LTD,88E,88E,United Kingdom,LSE,GBP
2,japan,A Dot,A Dot Co Ltd,JPY,7063,equity,JP3160590000,A DOT CO LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,hong kong,AAC Technologies,AAC Technologies Holdings Inc,HKD,2018,equity,KYG2953R1149,AAC TECHNOLOGIES HOLDINGS IN,Industrial,AAC TECHNOLOGIES HOLDINGS IN,2018,2018,NaN,NaN,NaN
4,hong kong,AAG Energy Holdings Ltd,AAG Energy Holdings Ltd,HKD,2686,equity,KYG000371040,AAG ENERGY HOLDINGS LTD,Energy,AAG ENERGY HOLDINGS LTD,2686,2686,Hong Kong,SEHK,HKD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17754,NaN,NaN,NaN,NaN,NaN,NaN,CA98985W1023,ZYMEWORKS INC,"Consumer, Non-cyclical",ZYMEWORKS INC,ZYME,ZYME,NaN,NaN,NaN
17755,NaN,NaN,NaN,NaN,NaN,NaN,US98986X1090,ZYNERBA PHARMACEUTICALS INC,"Consumer, Non-cyclical",ZYNERBA PHARMACEUTICALS INC,NMS,ZYNE,NaN,NaN,NaN
17756,NaN,NaN,NaN,NaN,NaN,NaN,US98986M1036,ZYNEX INC,"Consumer, Non-cyclical",ZYNEX INC,NMS,ZYXI,NaN,NaN,NaN
17757,NaN,NaN,NaN,NaN,NaN,NaN,US98986T1088,ZYNGA INC - CL A,Technology,ZYNGA INC - CL A,ZNGA,ZNGA,NaN,NaN,NaN
17758,NaN,NaN,NaN,NaN,NaN,NaN,GB0006971013,ZYTRONIC PLC,Industrial,ZYTRONIC PLC,ASQ1,ZYT,United Kingdom,LSE,GBP

In [3]:
df_notNull = df_isin[~df_isin['ISIN'].isnull()].copy()
df_notNull

,country-Inv,name-Inv,full_name-Inv,currency-Inv,symbol-Inv,asset_class-Inv,ISIN,Name_197,industry-IB,longName-IB,marketName-IB,Symbol-IB,Country-IB,Exchange-IB,Currency-IB
0,united states,2U Inc,2U Inc,USD,TWOU,equity,US90214J1016,2U INC,"Consumer, Non-cyclical",2U INC,NMS,TWOU,NaN,NaN,NaN
1,united kingdom,88 Energy,88 Energy Ltd,GBP,88E,equity,AU00000088E2,88 ENERGY LTD,Energy,88 ENERGY LTD,88E,88E,United Kingdom,LSE,GBP
2,japan,A Dot,A Dot Co Ltd,JPY,7063,equity,JP3160590000,A DOT CO LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,hong kong,AAC Technologies,AAC Technologies Holdings Inc,HKD,2018,equity,KYG2953R1149,AAC TECHNOLOGIES HOLDINGS IN,Industrial,AAC TECHNOLOGIES HOLDINGS IN,2018,2018,NaN,NaN,NaN
4,hong kong,AAG Energy Holdings Ltd,AAG Energy Holdings Ltd,HKD,2686,equity,KYG000371040,AAG ENERGY HOLDINGS LTD,Energy,AAG ENERGY HOLDINGS LTD,2686,2686,Hong Kong,SEHK,HKD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17754,NaN,NaN,NaN,NaN,NaN,NaN,CA98985W1023,ZYMEWORKS INC,"Consumer, Non-cyclical",ZYMEWORKS INC,ZYME,ZYME,NaN,NaN,NaN
17755,NaN,NaN,NaN,NaN,NaN,NaN,US98986X1090,ZYNERBA PHARMACEUTICALS INC,"Consumer, Non-cyclical",ZYNERBA PHARMACEUTICALS INC,NMS,ZYNE,NaN,NaN,NaN
17756,NaN,NaN,NaN,NaN,NaN,NaN,US98986M1036,ZYNEX INC,"Consumer, Non-cyclical",ZYNEX INC,NMS,ZYXI,NaN,NaN,NaN
17757,NaN,NaN,NaN,NaN,NaN,NaN,US98986T1088,ZYNGA INC - CL A,Technology,ZYNGA INC - CL A,ZNGA,ZNGA,NaN,NaN,NaN
17758,NaN,NaN,NaN,NaN,NaN,NaN,GB0006971013,ZYTRONIC PLC,Industrial,ZYTRONIC PLC,ASQ1,ZYT,United Kingdom,LSE,GBP

In [7]:
df_eod = pd.DataFrame()
for isin in df_notNull["ISIN"]:
    if str(isin) != 'nan':
        path = "https://eodhistoricaldata.com/api/search/"+str(isin)+"?api_token=5f3afd582bd7b4.95720069"
        
        df = pd.read_json(path) 
        if len(df) != 0:
            df_eod = df_eod.append(df.iloc[0], ignore_index=True)
            
    if len(df_eod) % (len(df_notNull)//5) == 0:
        print("progress: %.2f" % (100*len(df_eod)/len(df_notNull)) + "%")

progress: 20.00%
progress: 39.99%
progress: 39.99%
progress: 59.99%
progress: 59.99%

In [8]:
df_eod

,Code,Country,Currency,Exchange,ISIN,Name,Type,previousClose,previousCloseDate
0,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02
1,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03
2,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2064.000,2022-08-03
3,2018,Hong Kong,HKD,HK,KYG2953R1149,AAC Technologies Holdings Inc,Common Stock,14.580,2022-08-03
4,2686,Hong Kong,HKD,HK,KYG000371040,AAG Energy Holdings Ltd,Common Stock,1.410,2022-08-03
...,...,...,...,...,...,...,...,...,...
13170,ZYDUSWELL,India,INR,NSE,INE768C01010,Zydus Wellness Limited,Common Stock,1579.700,2022-08-03
13171,ZYME,USA,USD,US,CA98985W1023,Zymeworks Inc,Common Stock,6.260,2022-08-03
13172,ZYNE,USA,USD,US,US98986X1090,Zynerba Pharmaceuticals Inc,Common Stock,1.170,2022-08-03
13173,ZYXI,USA,USD,US,US98986M1036,Zynex Inc,Common Stock,8.400,2022-08-03
13174,ZYT,UK,GBX,LSE,GB0006971013,Zytronic,Common Stock,140.000,2022-08-03

In [9]:
data = pd.merge(df_eod, df_isin, how='outer', on='ISIN')
data

,Code,Country,Currency,Exchange,ISIN,Name,Type,previousClose,previousCloseDate,country-Inv,...,symbol-Inv,asset_class-Inv,Name_197,industry-IB,longName-IB,marketName-IB,Symbol-IB,Country-IB,Exchange-IB,Currency-IB
0,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02,united states,...,TWOU,equity,2U INC,"Consumer, Non-cyclical",2U INC,NMS,TWOU,NaN,NaN,NaN
1,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03,united kingdom,...,88E,equity,88 ENERGY LTD,Energy,88 ENERGY LTD,88E,88E,United Kingdom,LSE,GBP
2,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2064.000,2022-08-03,japan,...,7063,equity,A DOT CO LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018,Hong Kong,HKD,HK,KYG2953R1149,AAC Technologies Holdings Inc,Common Stock,14.580,2022-08-03,hong kong,...,2018,equity,AAC TECHNOLOGIES HOLDINGS IN,Industrial,AAC TECHNOLOGIES HOLDINGS IN,2018,2018,NaN,NaN,NaN
4,2686,Hong Kong,HKD,HK,KYG000371040,AAG Energy Holdings Ltd,Common Stock,1.410,2022-08-03,hong kong,...,2686,equity,AAG ENERGY HOLDINGS LTD,Energy,AAG ENERGY HOLDINGS LTD,2686,2686,Hong Kong,SEHK,HKD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18557,NaN,NaN,NaN,NaN,US98979J1097,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZOE'S KITCHEN INC,"Consumer, Cyclical",ZOE'S KITCHEN INC,ZOES,ZOES,NaN,NaN,NaN
18558,NaN,NaN,NaN,NaN,CA98977K1084,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZOLOTO RESOURCES LTD,Basic Materials,ZOLOTO RESOURCES LTD,ZR,ZR,NaN,NaN,NaN
18559,NaN,NaN,NaN,NaN,CA98977R1038,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZOOMMED INC,Technology,ZOOMMED INC,ZMD.H,ZMD.H,NaN,NaN,NaN
18560,NaN,NaN,NaN,NaN,GB00BMHTHT14,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZPG PLC,Communications,ZPG PLC,ZPG,ZPG,NaN,NaN,NaN
18561,NaN,NaN,NaN,NaN,US98986T1088,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZYNGA INC - CL A,Technology,ZYNGA INC - CL A,ZNGA,ZNGA,NaN,NaN,NaN

In [10]:
data = data.rename(columns={"Code": "Code-EOD", "Country": "Country-EOD", "Currency": "Currency-EOD", "Exchange": "Exchange-EOD", "Name": "Name-EOD" , "Type": "Type-EOD" , "previousClose": "previousClose-EOD" , "previousCloseDate": "previousCloseDate-EOD"})
data

,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD,previousCloseDate-EOD,country-Inv,...,symbol-Inv,asset_class-Inv,Name_197,industry-IB,longName-IB,marketName-IB,Symbol-IB,Country-IB,Exchange-IB,Currency-IB
0,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02,united states,...,TWOU,equity,2U INC,"Consumer, Non-cyclical",2U INC,NMS,TWOU,NaN,NaN,NaN
1,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03,united kingdom,...,88E,equity,88 ENERGY LTD,Energy,88 ENERGY LTD,88E,88E,United Kingdom,LSE,GBP
2,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2064.000,2022-08-03,japan,...,7063,equity,A DOT CO LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018,Hong Kong,HKD,HK,KYG2953R1149,AAC Technologies Holdings Inc,Common Stock,14.580,2022-08-03,hong kong,...,2018,equity,AAC TECHNOLOGIES HOLDINGS IN,Industrial,AAC TECHNOLOGIES HOLDINGS IN,2018,2018,NaN,NaN,NaN
4,2686,Hong Kong,HKD,HK,KYG000371040,AAG Energy Holdings Ltd,Common Stock,1.410,2022-08-03,hong kong,...,2686,equity,AAG ENERGY HOLDINGS LTD,Energy,AAG ENERGY HOLDINGS LTD,2686,2686,Hong Kong,SEHK,HKD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18557,NaN,NaN,NaN,NaN,US98979J1097,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZOE'S KITCHEN INC,"Consumer, Cyclical",ZOE'S KITCHEN INC,ZOES,ZOES,NaN,NaN,NaN
18558,NaN,NaN,NaN,NaN,CA98977K1084,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZOLOTO RESOURCES LTD,Basic Materials,ZOLOTO RESOURCES LTD,ZR,ZR,NaN,NaN,NaN
18559,NaN,NaN,NaN,NaN,CA98977R1038,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZOOMMED INC,Technology,ZOOMMED INC,ZMD.H,ZMD.H,NaN,NaN,NaN
18560,NaN,NaN,NaN,NaN,GB00BMHTHT14,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZPG PLC,Communications,ZPG PLC,ZPG,ZPG,NaN,NaN,NaN
18561,NaN,NaN,NaN,NaN,US98986T1088,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZYNGA INC - CL A,Technology,ZYNGA INC - CL A,ZNGA,ZNGA,NaN,NaN,NaN

In [11]:
data = data.drop_duplicates(subset=['ISIN'])

data

,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD,previousCloseDate-EOD,country-Inv,...,symbol-Inv,asset_class-Inv,Name_197,industry-IB,longName-IB,marketName-IB,Symbol-IB,Country-IB,Exchange-IB,Currency-IB
0,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02,united states,...,TWOU,equity,2U INC,"Consumer, Non-cyclical",2U INC,NMS,TWOU,NaN,NaN,NaN
1,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03,united kingdom,...,88E,equity,88 ENERGY LTD,Energy,88 ENERGY LTD,88E,88E,United Kingdom,LSE,GBP
2,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2064.000,2022-08-03,japan,...,7063,equity,A DOT CO LTD,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018,Hong Kong,HKD,HK,KYG2953R1149,AAC Technologies Holdings Inc,Common Stock,14.580,2022-08-03,hong kong,...,2018,equity,AAC TECHNOLOGIES HOLDINGS IN,Industrial,AAC TECHNOLOGIES HOLDINGS IN,2018,2018,NaN,NaN,NaN
4,2686,Hong Kong,HKD,HK,KYG000371040,AAG Energy Holdings Ltd,Common Stock,1.410,2022-08-03,hong kong,...,2686,equity,AAG ENERGY HOLDINGS LTD,Energy,AAG ENERGY HOLDINGS LTD,2686,2686,Hong Kong,SEHK,HKD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18557,NaN,NaN,NaN,NaN,US98979J1097,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZOE'S KITCHEN INC,"Consumer, Cyclical",ZOE'S KITCHEN INC,ZOES,ZOES,NaN,NaN,NaN
18558,NaN,NaN,NaN,NaN,CA98977K1084,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZOLOTO RESOURCES LTD,Basic Materials,ZOLOTO RESOURCES LTD,ZR,ZR,NaN,NaN,NaN
18559,NaN,NaN,NaN,NaN,CA98977R1038,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZOOMMED INC,Technology,ZOOMMED INC,ZMD.H,ZMD.H,NaN,NaN,NaN
18560,NaN,NaN,NaN,NaN,GB00BMHTHT14,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZPG PLC,Communications,ZPG PLC,ZPG,ZPG,NaN,NaN,NaN
18561,NaN,NaN,NaN,NaN,US98986T1088,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,ZYNGA INC - CL A,Technology,ZYNGA INC - CL A,ZNGA,ZNGA,NaN,NaN,NaN

In [12]:
data.to_csv('withEOD.csv', index=False)

In [13]:
len(data['ISIN'].unique())

17511