In [11]:
import numpy as np  
import pandas as pd

In [12]:
path = "./Data/withFIGI.csv"

df = pd.read_csv(path, index_col=0)  
df

,Name_197,Exchange_197,Country_197,Currency_197,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,...,figi,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI,Not_Match,Source_Available
0,1ST GROUP LTD,ASX,Australia,AUD,1ST,Australia,AUD,AU,AU0000001ST0,1stAvailable Ltd,...,BBG008HNLRF4,BBG008HNLRF4,BBG008HNLRG3,AU,Equity,1ST,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
1,2U INC,NASDAQ,United States of America,USD,TWOU,USA,USD,US,US90214J1016,2U Inc,...,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock,NaN,FIGI;Inv;IB;EOD;
2,3DX INDUSTRIES INC,PINK,United States of America,USD,DDDX,USA,USD,US,US88556A1007,3Dx Industries Inc,...,BBG000C129N6,BBG000C129N6,BBG001STRH79,US,Equity,DDDX,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
3,3M CO,US Exchange,Mexico,NaN,MMM,USA,USD,US,US88579Y1010,3M Company,...,BBG000BP52R2,BBG000BP52R2,BBG001S5T7X2,US,Equity,MMM,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
4,88 ENERGY LTD,LSE,United Kingdom,GBP,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,...,BBG000BWTTK9,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock,NaN,FIGI;Inv;IB;EOD;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20217,ZYNERBA PHARMACEUTICALS INC,NASDAQ,United States of America,USD,ZYNE,USA,USD,US,US98986X1090,Zynerba Pharmaceuticals Inc,...,BBG007BBS8B7,BBG007BBS8B7,BBG007BBS8C6,US,Equity,ZYNE,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
20218,ZYNEX INC,NASDAQ,United States of America,USD,ZYXI,USA,USD,US,US98986M1036,Zynex Inc,...,BBG000BJBXZ2,BBG000BJBXZ2,BBG001S7T7V0,US,Equity,ZYXI,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
20219,ZYNGA INC - CL A,NASDAQ,Switzerland,USD,NaN,NaN,NaN,NaN,US98986T1088,NaN,...,BBG005YZL376,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock,NaN,FIGI;IB;
20220,ZYTRONIC PLC,LSE,United Kingdom,GBP,ZYT,UK,GBX,LSE,GB0006971013,Zytronic,...,BBG000BZPV76,BBG000BZPTJ8,BBG001SFLP13,LN,Equity,ZYT,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
20221,ZZ CAPITAL INTERNATIONAL LTD,SEHK,Hong Kong,HKD,NaN,NaN,NaN,NaN,KYG9895T1085,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Inv;

In [13]:
df = df.drop(['Not_Match', 'Source_Available'], axis=1)

df

,Name_197,Exchange_197,Country_197,Currency_197,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,...,longName-FIGI,symbol-FIGI,figi,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI
0,1ST GROUP LTD,ASX,Australia,AUD,1ST,Australia,AUD,AU,AU0000001ST0,1stAvailable Ltd,...,1ST GROUP LTD,1ST,BBG008HNLRF4,BBG008HNLRF4,BBG008HNLRG3,AU,Equity,1ST,Common Stock,Common Stock
1,2U INC,NASDAQ,United States of America,USD,TWOU,USA,USD,US,US90214J1016,2U Inc,...,2U INC,TWOU,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock
2,3DX INDUSTRIES INC,PINK,United States of America,USD,DDDX,USA,USD,US,US88556A1007,3Dx Industries Inc,...,3DX INDUSTRIES INC,DDDX,BBG000C129N6,BBG000C129N6,BBG001STRH79,US,Equity,DDDX,Common Stock,Common Stock
3,3M CO,US Exchange,Mexico,NaN,MMM,USA,USD,US,US88579Y1010,3M Company,...,3M CO,MMM,BBG000BP52R2,BBG000BP52R2,BBG001S5T7X2,US,Equity,MMM,Common Stock,Common Stock
4,88 ENERGY LTD,LSE,United Kingdom,GBP,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,...,88 ENERGY LTD,POQ,BBG000BWTTK9,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20217,ZYNERBA PHARMACEUTICALS INC,NASDAQ,United States of America,USD,ZYNE,USA,USD,US,US98986X1090,Zynerba Pharmaceuticals Inc,...,ZYNERBA PHARMACEUTICALS INC,ZYNE,BBG007BBS8B7,BBG007BBS8B7,BBG007BBS8C6,US,Equity,ZYNE,Common Stock,Common Stock
20218,ZYNEX INC,NASDAQ,United States of America,USD,ZYXI,USA,USD,US,US98986M1036,Zynex Inc,...,ZYNEX INC,ZYXI,BBG000BJBXZ2,BBG000BJBXZ2,BBG001S7T7V0,US,Equity,ZYXI,Common Stock,Common Stock
20219,ZYNGA INC - CL A,NASDAQ,Switzerland,USD,NaN,NaN,NaN,NaN,US98986T1088,NaN,...,ZYNGA INC - CL A,ZNGAEUR,BBG005YZL376,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock
20220,ZYTRONIC PLC,LSE,United Kingdom,GBP,ZYT,UK,GBX,LSE,GB0006971013,Zytronic,...,ZYTRONIC PLC,ZYT,BBG000BZPV76,BBG000BZPTJ8,BBG001SFLP13,LN,Equity,ZYT,Common Stock,Common Stock
20221,ZZ CAPITAL INTERNATIONAL LTD,SEHK,Hong Kong,HKD,NaN,NaN,NaN,NaN,KYG9895T1085,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Country, Sector/Industry, Exchange, ISIN, FIGI

In [17]:
df_ck = df.copy()
df_ck['Ranking'] = 0

columns = ['Country-EOD', 'Exchange-EOD', 'ISIN', 'country-Inv', 
           'figi', 'exchCode-FIGI']

for col in columns:
    df_ck.loc[~df_ck[col].isnull(),'Ranking'] = 1 + df_ck['Ranking'].astype(int)

df_ck[['Name_197','Ranking']]

                           Name_197  Ranking
0                     1ST GROUP LTD        5
1                            2U INC        6
2                3DX INDUSTRIES INC        5
3                             3M CO        5
4                     88 ENERGY LTD        6
...                             ...      ...
20217   ZYNERBA PHARMACEUTICALS INC        5
20218                     ZYNEX INC        5
20219              ZYNGA INC - CL A        3
20220                  ZYTRONIC PLC        5
20221  ZZ CAPITAL INTERNATIONAL LTD        2

[19565 rows x 2 columns]

In [18]:
df_ck['Ranking'].value_counts().to_frame()

   Ranking
5     7721
6     5235
0     2129
3     1853
1     1749
4      659
2      219