In [91]:
import numpy as np
import pandas as pd
import requests

In [92]:
path = "./Investing_IB_197.csv"

df_isin = pd.read_csv(path)  
df_isin

,Ticker,Name-IB,Country-IB,Exchange-IB,Currency-IB,ISIN-19.7,ISIN-IB,Name-Investing.com,Exchange-Investing.com,Type-Investing.com,Market-Investing.com,ISIN,CUSIP-Investing.com
0,1ST,1ST GROUP LTD,Australia,ASX,AUD,NaN,AU0000001ST0,NaN,NaN,NaN,NaN,AU0000001ST0,NaN
1,TWOU,2U INC,United States of America,NASDAQ,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DDDX,3DX INDUSTRIES INC,United States of America,PINK,USD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MMM,3M CO,Mexico,US Exchange,NaN,NaN,NaN,3M Company,NYSE,Equity,United States,US88579Y1010,88579Y101
4,88E,88 ENERGY LTD,United Kingdom,LSE,GBP,AU00000088E2,AU00000088E2,NaN,NaN,NaN,NaN,AU00000088E2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19896,EDMCQ,NaN,NaN,NaN,NaN,NaN,NaN,Education Management Corp,OTC Markets,Equity,United States,US28140M1036,28140M103
19897,EDSFF,NaN,NaN,NaN,NaN,NaN,NaN,Exceed Company Ltd,OTC Markets,Equity,United States,VGG323351046,G32335104
19898,FALC,NaN,NaN,NaN,NaN,NaN,NaN,FalconStor Software Inc,OTC Markets,Equity,United States,US3061372096,306137209
19899,FBSI,NaN,NaN,NaN,NaN,NaN,NaN,First Bancshares Inc,OTC Markets,Equity,United States,US3186871006,318687100
19900,FFDF,NaN,NaN,NaN,NaN,NaN,NaN,FFD Financial Corp,OTC Markets,Equity,United States,US30243C1071,30243C107

In [93]:
df_notNull = df_isin[~df_isin['ISIN'].isnull()].copy()
df_notNull

,Ticker,Name-IB,Country-IB,Exchange-IB,Currency-IB,ISIN-19.7,ISIN-IB,Name-Investing.com,Exchange-Investing.com,Type-Investing.com,Market-Investing.com,ISIN,CUSIP-Investing.com
0,1ST,1ST GROUP LTD,Australia,ASX,AUD,NaN,AU0000001ST0,NaN,NaN,NaN,NaN,AU0000001ST0,NaN
3,MMM,3M CO,Mexico,US Exchange,NaN,NaN,NaN,3M Company,NYSE,Equity,United States,US88579Y1010,88579Y101
4,88E,88 ENERGY LTD,United Kingdom,LSE,GBP,AU00000088E2,AU00000088E2,NaN,NaN,NaN,NaN,AU00000088E2,NaN
6,7063,A DOT CO LTD,Japan,TSEJ,JPY,JP3160590000,JP3160590000,NaN,NaN,NaN,NaN,JP3160590000,NaN
8,MLATV,A TOUTE VITESSE-ATV,France,SBF,EUR,NaN,FR0010050773,NaN,NaN,NaN,NaN,FR0010050773,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19896,EDMCQ,NaN,NaN,NaN,NaN,NaN,NaN,Education Management Corp,OTC Markets,Equity,United States,US28140M1036,28140M103
19897,EDSFF,NaN,NaN,NaN,NaN,NaN,NaN,Exceed Company Ltd,OTC Markets,Equity,United States,VGG323351046,G32335104
19898,FALC,NaN,NaN,NaN,NaN,NaN,NaN,FalconStor Software Inc,OTC Markets,Equity,United States,US3061372096,306137209
19899,FBSI,NaN,NaN,NaN,NaN,NaN,NaN,First Bancshares Inc,OTC Markets,Equity,United States,US3186871006,318687100
19900,FFDF,NaN,NaN,NaN,NaN,NaN,NaN,FFD Financial Corp,OTC Markets,Equity,United States,US30243C1071,30243C107

In [94]:
df_eod = pd.DataFrame()
for isin in df_notNull["ISIN"]:
    if str(isin) != 'nan':
        path = "https://eodhistoricaldata.com/api/search/"+str(isin)+"?api_token=5f3afd582bd7b4.95720069"
        
        df = pd.read_json(path) 
        if len(df) != 0:
            df_eod = df_eod.append(df.iloc[0], ignore_index=True)

In [97]:
df_eod

,Code,Country,Currency,Exchange,ISIN,Name,Type,previousClose,previousCloseDate
0,1ST,Australia,AUD,AU,AU0000001ST0,1stAvailable Ltd,Common Stock,0.0080,2022-07-21
1,MMM,USA,USD,US,US88579Y1010,3M Company,Common Stock,133.9500,2022-07-21
2,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.7250,2022-07-21
3,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2136.0000,2022-07-21
4,AMRK,Israel,ILA,TA,IL0010922040,Amir Marketing and Investments in Agriculture Ltd,Common Stock,3911.0000,2022-07-21
...,...,...,...,...,...,...,...,...,...
8037,EDMCQ,USA,USD,US,US28140M1036,Education Management Corp,Common Stock,0.0001,2022-07-21
8038,EDSFF,USA,USD,US,VGG323351046,Exceed Company Ltd,Common Stock,0.0001,2022-07-21
8039,FALC,USA,USD,US,US3061372096,FalconStor Software Inc,Common Stock,1.1700,2022-07-21
8040,FBSI,USA,USD,US,US3186871006,First Bancshares Inc,Common Stock,17.5000,2022-07-21
8041,FFDF,USA,USD,US,US30243C1071,FFD Financial Corp,Common Stock,35.0000,2022-07-21

In [100]:
data = pd.merge(df_eod, df_isin, how='outer', on='ISIN')
data

,Code,Country,Currency,Exchange,ISIN,Name,Type,previousClose,previousCloseDate,Ticker,...,Country-IB,Exchange-IB,Currency-IB,ISIN-19.7,ISIN-IB,Name-Investing.com,Exchange-Investing.com,Type-Investing.com,Market-Investing.com,CUSIP-Investing.com
0,1ST,Australia,AUD,AU,AU0000001ST0,1stAvailable Ltd,Common Stock,0.008,2022-07-21,1ST,...,Australia,ASX,AUD,NaN,AU0000001ST0,NaN,NaN,NaN,NaN,NaN
1,MMM,USA,USD,US,US88579Y1010,3M Company,Common Stock,133.950,2022-07-21,MMM,...,Mexico,US Exchange,NaN,NaN,NaN,3M Company,NYSE,Equity,United States,88579Y101
2,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.725,2022-07-21,88E,...,United Kingdom,LSE,GBP,AU00000088E2,AU00000088E2,NaN,NaN,NaN,NaN,NaN
3,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2136.000,2022-07-21,7063,...,Japan,TSEJ,JPY,JP3160590000,JP3160590000,NaN,NaN,NaN,NaN,NaN
4,AMRK,Israel,ILA,TA,IL0010922040,Amir Marketing and Investments in Agriculture Ltd,Common Stock,3911.000,2022-07-21,AMRK,...,Israel,TASE,ILS,NaN,IL0010922040,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20041,NaN,NaN,NaN,NaN,NZZELE0001S1,NaN,NaN,NaN,NaN,ZEL,...,Australia,ASX,AUD,NZZELE0001S1,NZZELE0001S1,NaN,NaN,NaN,NaN,NaN
20042,NaN,NaN,NaN,NaN,ZM0000000201,NaN,NaN,NaN,NaN,ZAM,...,United Kingdom,LSE,GBP,NaN,ZM0000000201,NaN,NaN,NaN,NaN,NaN
20043,NaN,NaN,NaN,NaN,CA98935P1080,NaN,NaN,NaN,NaN,ZEN,...,Canada,VENTURE,CAD,CA98935P1080,CA98935P1080,NaN,NaN,NaN,NaN,NaN
20044,NaN,NaN,NaN,NaN,AU000000ZYB8,NaN,NaN,NaN,NaN,ZYB,...,Australia,ASX,AUD,AU000000ZYB8,AU000000ZYB8,NaN,NaN,NaN,NaN,NaN
20045,NaN,NaN,NaN,NaN,US2836782092,NaN,NaN,NaN,NaN,EP_pc,...,NaN,NaN,NaN,NaN,NaN,El Paso Energy Capital Trust I,NYSE,Equity,United States,283678209

In [101]:
data = data.rename(columns={"Code": "Code-EOD", "Country": "Country-EOD", "Currency": "Currency-EOD", "Exchange": "Exchange-EOD", "Name": "Name-EOD" , "Type": "Type-EOD" , "previousClose": "previousClose-EOD" , "previousCloseDate": "previousCloseDate-EOD"})
data

,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD,previousCloseDate-EOD,Ticker,...,Country-IB,Exchange-IB,Currency-IB,ISIN-19.7,ISIN-IB,Name-Investing.com,Exchange-Investing.com,Type-Investing.com,Market-Investing.com,CUSIP-Investing.com
0,1ST,Australia,AUD,AU,AU0000001ST0,1stAvailable Ltd,Common Stock,0.008,2022-07-21,1ST,...,Australia,ASX,AUD,NaN,AU0000001ST0,NaN,NaN,NaN,NaN,NaN
1,MMM,USA,USD,US,US88579Y1010,3M Company,Common Stock,133.950,2022-07-21,MMM,...,Mexico,US Exchange,NaN,NaN,NaN,3M Company,NYSE,Equity,United States,88579Y101
2,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.725,2022-07-21,88E,...,United Kingdom,LSE,GBP,AU00000088E2,AU00000088E2,NaN,NaN,NaN,NaN,NaN
3,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2136.000,2022-07-21,7063,...,Japan,TSEJ,JPY,JP3160590000,JP3160590000,NaN,NaN,NaN,NaN,NaN
4,AMRK,Israel,ILA,TA,IL0010922040,Amir Marketing and Investments in Agriculture Ltd,Common Stock,3911.000,2022-07-21,AMRK,...,Israel,TASE,ILS,NaN,IL0010922040,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20041,NaN,NaN,NaN,NaN,NZZELE0001S1,NaN,NaN,NaN,NaN,ZEL,...,Australia,ASX,AUD,NZZELE0001S1,NZZELE0001S1,NaN,NaN,NaN,NaN,NaN
20042,NaN,NaN,NaN,NaN,ZM0000000201,NaN,NaN,NaN,NaN,ZAM,...,United Kingdom,LSE,GBP,NaN,ZM0000000201,NaN,NaN,NaN,NaN,NaN
20043,NaN,NaN,NaN,NaN,CA98935P1080,NaN,NaN,NaN,NaN,ZEN,...,Canada,VENTURE,CAD,CA98935P1080,CA98935P1080,NaN,NaN,NaN,NaN,NaN
20044,NaN,NaN,NaN,NaN,AU000000ZYB8,NaN,NaN,NaN,NaN,ZYB,...,Australia,ASX,AUD,AU000000ZYB8,AU000000ZYB8,NaN,NaN,NaN,NaN,NaN
20045,NaN,NaN,NaN,NaN,US2836782092,NaN,NaN,NaN,NaN,EP_pc,...,NaN,NaN,NaN,NaN,NaN,El Paso Energy Capital Trust I,NYSE,Equity,United States,283678209

In [96]:
df_eod.to_csv('EOD.csv', index=False)

In [102]:
data.to_csv('withEOD.csv', index=False)