In [11]:
import numpy as np  
import pandas as pd 
import requests

In [37]:
path = "./Data/withFIGI.csv"

df_meta = pd.read_csv(path, index_col=0)  
df_meta

,Name_197,Exchange_197,Country_197,Currency_197,stockType_197,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,...,figi,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI,Not_Match,Source_Available
0,1ST GROUP LTD,ASX,Australia,AUD,COMMON,1ST,Australia,AUD,AU,AU0000001ST0,...,BBG008HNLRF4,BBG008HNLRF4,BBG008HNLRG3,AU,Equity,1ST,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
1,2U INC,NASDAQ,United States of America,USD,COMMON,TWOU,USA,USD,US,US90214J1016,...,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock,NaN,FIGI;Inv;IB;EOD;
2,3DX INDUSTRIES INC,PINK,United States of America,USD,COMMON,DDDX,USA,USD,US,US88556A1007,...,BBG000C129N6,BBG000C129N6,BBG001STRH79,US,Equity,DDDX,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
3,3M CO,US Exchange,Mexico,NaN,NaN,MMM,USA,USD,US,US88579Y1010,...,BBG000BP52R2,BBG000BP52R2,BBG001S5T7X2,US,Equity,MMM,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
4,88 ENERGY LTD,LSE,United Kingdom,GBP,COMMON,88E,UK,GBX,LSE,AU00000088E2,...,BBG000BWTTK9,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock,NaN,FIGI;Inv;IB;EOD;
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19731,ZYNERBA PHARMACEUTICALS INC,NASDAQ,United States of America,USD,COMMON,ZYNE,USA,USD,US,US98986X1090,...,BBG007BBS8B7,BBG007BBS8B7,BBG007BBS8C6,US,Equity,ZYNE,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
19732,ZYNEX INC,NASDAQ,United States of America,USD,COMMON,ZYXI,USA,USD,US,US98986M1036,...,BBG000BJBXZ2,BBG000BJBXZ2,BBG001S7T7V0,US,Equity,ZYXI,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
19733,ZYNGA INC - CL A,NASDAQ,Switzerland,USD,COMMON,NaN,NaN,NaN,NaN,US98986T1088,...,BBG005YZL376,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock,NaN,FIGI;IB;
19734,ZYTRONIC PLC,LSE,United Kingdom,GBP,COMMON,ZYT,UK,GBX,LSE,GB0006971013,...,BBG000BZPV76,BBG000BZPTJ8,BBG001SFLP13,LN,Equity,ZYT,Common Stock,Common Stock,NaN,FIGI;IB;EOD;
19735,ZZ CAPITAL INTERNATIONAL LTD,SEHK,Hong Kong,HKD,COMMON,NaN,NaN,NaN,NaN,KYG9895T1085,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Inv;

In [12]:
symbol_exchange = df["Code-EOD"]+"."+df["Exchange-EOD"]
symbol_exchange.sort_values(inplace=True)
symbol_exchange.dropna(inplace=True)
columns = ['Code', 'ISIN', 'CUSIP','Sector','Industry','GicSector','GicGroup','GicIndustry','GicSubIndustry']
df = pd.DataFrame(columns=columns)
df2 = pd.DataFrame(columns=columns)

In [13]:
for i in symbol_exchange:
    try:
        newdata=f'https://eodhistoricaldata.com/api/fundamentals/{i}?api_token=5f3afd582bd7b4.95720069'
        a = requests.get(newdata).json()
        train = pd.DataFrame.from_dict(a, orient='index')
        train.reset_index(level=0, inplace=True)
        train = train.iloc[0]
        new = train[columns].copy().to_frame().T
        df = pd.concat([df,new])

    except:
        df=pd.concat([df,df2])

In [35]:
df.rename(columns={'Code': 'Code-EODapi', 'CUSIP': 'CUSIP-EODapi', 'Sector': 'Sector-EODapi',
                  'Industry': 'Industry-EODapi', 'GicSector': 'GicSector-EODapi', 'GicGroup': 'GicGroup-EODapi',
                  'GicIndustry': 'GicIndustry-EODapi', 'GicSubIndustry': 'GicSubIndustry-EODapi'}, inplace=True)

df = df.dropna(subset=['ISIN'])

df

,Code-EODapi,ISIN,CUSIP-EODapi,Sector-EODapi,Industry-EODapi,GicSector-EODapi,GicGroup-EODapi,GicIndustry-EODapi,GicSubIndustry-EODapi
0,A,US00846U1016,00846U101,Healthcare,Diagnostics & Research,Health Care,"Pharmaceuticals, Biotechnology & Life Sciences",Life Sciences Tools & Services,Life Sciences Tools & Services
0,AA,US0138721065,013872106,Basic Materials,Aluminum,Materials,Materials,Metals & Mining,Aluminum
0,AAIC,US0413562051,NaN,Real Estate,REIT-Mortgage,Financials,Diversified Financials,Mortgage Real Estate Investment Trusts (REITs),Mortgage REITs
0,AAL,US02376R1023,001765106,Industrials,Airlines,Industrials,Transportation,Airlines,Airlines
0,AAMC,VI02153X1080,02153X108,Financial Services,Asset Management,Real Estate,Real Estate,Real Estate Management & Development,Real Estate Services
...,...,...,...,...,...,...,...,...,...
0,SLGN,US8270481091,827048109,Consumer Cyclical,Packaging & Containers,Materials,Materials,Containers & Packaging,Metal & Glass Containers
0,SLI,CA8536061010,NaN,Basic Materials,Other Industrial Metals & Mining,NaN,NaN,NaN,NaN
0,SLN,US82686Q1013,NaN,Healthcare,Biotechnology,NaN,NaN,NaN,NaN
0,SLNO,US8342032005,14066L105,Healthcare,Biotechnology,Health Care,"Pharmaceuticals, Biotechnology & Life Sciences",Biotechnology,Biotechnology
0,SLP,US8292141053,713831105,Healthcare,Health Information Services,Health Care,Health Care Equipment & Services,Health Care Technology,Health Care Technology

In [17]:
path = "./Data/stockmetadata_Abhir.csv"

df_ab = pd.read_csv(path, index_col=0)
df_ab

,Ticker,Exchange,Company_Name,E,S,G,ESG_Mean,STS_E,STS_S,STS_G,...,EOD-GicGroup,EOD-GicIndustry,EOD-GicSubIndustry,INV_country,INV_name,INV_full_name,INV_isin,INV_currency,INV_symbol,INV_asset_class
Timestamp,,,,,,,,,,,,,,,,,,,,,
2017-07-01,1ST,ASX,1ST GROUP LTD,NaN,NaN,NaN,NaN,0.632268,0.443666,0.388411,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-01,TWOU,NASDAQ,2U INC,NaN,NaN,NaN,NaN,0.309504,0.319239,0.201083,...,Software & Services,Software,Application Software,united states,2U Inc,2U Inc,US90214J1016,USD,TWOU,equity
2017-07-01,DDDX,PINK,3DX INDUSTRIES INC,NaN,NaN,NaN,NaN,-0.449226,-0.649688,-0.626188,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-01,MMM,US Exchange,3M CO,NaN,NaN,NaN,NaN,0.376139,0.301416,0.299159,...,Capital Goods,Industrial Conglomerates,Industrial Conglomerates,mexico,3M,3M Company,US88579Y1010,MXN,MMM,equity
2017-07-01,88E,LSE,88 ENERGY LTD,NaN,NaN,NaN,NaN,0.639011,0.822957,0.951858,...,NaN,NaN,NaN,united kingdom,88 Energy,88 Energy Ltd,AU00000088E2,GBP,88E,equity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-07-01,ZYNE,NASDAQ,ZYNERBA PHARMACEUTICALS INC,0.534073,0.534132,0.448869,0.505691,-0.025743,0.105700,0.047410,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-01,ZYXI,NASDAQ,ZYNEX INC,NaN,NaN,NaN,NaN,0.194208,0.217249,0.146417,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2017-07-01,ZNGA,NASDAQ,ZYNGA INC - CL A,-0.877308,-1.913663,-1.934595,-1.575189,-0.932901,-0.896336,-1.061539,...,NaN,NaN,NaN,united states,Zynga,Zynga Inc,US98986T1088,USD,ZNGA,equity
2017-07-01,ZYT,LSE,ZYTRONIC PLC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,united kingdom,Zytronic,Zytronic,GB0006971013,GBP,ZYT,equity
2017-07-01,8295,SEHK,ZZ CAPITAL INTERNATIONAL LTD,NaN,NaN,NaN,NaN,0.031431,0.024081,0.030556,...,NaN,NaN,NaN,brazil,Hedge Top Fofii 3 FII,Hedge Top Fofii 3 Fundo De Investimento Imobil...,NaN,BRL,HFOF11,equity

In [33]:
df_ab.rename(columns={'isindb-ISIN': 'ISIN'}, inplace=True)

df_isindb = df_ab[['isindb-Type', 'ISIN']].dropna(subset=['ISIN'])

df_isindb

           isindb-Type          ISIN
Timestamp
2017-07-01      Equity  US88579Y1010
2017-07-01         NaN  US00089Y1091
2017-07-01         NaN  US00202F1021
2017-07-01         NaN  FR0010050773
2017-07-01         NaN  KYG2953R1149
...                ...           ...
2017-07-01      EQUITY  CH0042615283
2017-07-01      Equity  CH0011075394
2017-07-01      Equity  HU0000074844
2017-07-01         NaN  US98986T1088
2017-07-01         NaN  GB0006971013

[7959 rows x 2 columns]

In [38]:
df_meta = pd.merge(df_meta, df, how='left', on='ISIN')
df_meta = pd.merge(df_meta, df_isindb, how='left', on='ISIN')

df_meta

,Name_197,Exchange_197,Country_197,Currency_197,stockType_197,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,...,Source_Available,Code-EODapi,CUSIP-EODapi,Sector-EODapi,Industry-EODapi,GicSector-EODapi,GicGroup-EODapi,GicIndustry-EODapi,GicSubIndustry-EODapi,isindb-Type
0,1ST GROUP LTD,ASX,Australia,AUD,COMMON,1ST,Australia,AUD,AU,AU0000001ST0,...,FIGI;IB;EOD;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2U INC,NASDAQ,United States of America,USD,COMMON,TWOU,USA,USD,US,US90214J1016,...,FIGI;Inv;IB;EOD;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3DX INDUSTRIES INC,PINK,United States of America,USD,COMMON,DDDX,USA,USD,US,US88556A1007,...,FIGI;IB;EOD;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3M CO,US Exchange,Mexico,NaN,NaN,MMM,USA,USD,US,US88579Y1010,...,FIGI;IB;EOD;,MMM,604059105,Industrials,Conglomerates,Industrials,Capital Goods,Industrial Conglomerates,Industrial Conglomerates,Equity
4,88 ENERGY LTD,LSE,United Kingdom,GBP,COMMON,88E,UK,GBX,LSE,AU00000088E2,...,FIGI;Inv;IB;EOD;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19826,ZYNERBA PHARMACEUTICALS INC,NASDAQ,United States of America,USD,COMMON,ZYNE,USA,USD,US,US98986X1090,...,FIGI;IB;EOD;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19827,ZYNEX INC,NASDAQ,United States of America,USD,COMMON,ZYXI,USA,USD,US,US98986M1036,...,FIGI;IB;EOD;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19828,ZYNGA INC - CL A,NASDAQ,Switzerland,USD,COMMON,NaN,NaN,NaN,NaN,US98986T1088,...,FIGI;IB;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19829,ZYTRONIC PLC,LSE,United Kingdom,GBP,COMMON,ZYT,UK,GBX,LSE,GB0006971013,...,FIGI;IB;EOD;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19830,ZZ CAPITAL INTERNATIONAL LTD,SEHK,Hong Kong,HKD,COMMON,NaN,NaN,NaN,NaN,KYG9895T1085,...,Inv;,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN