In [43]:
import requests     
import json         
import pandas as pd 
import numpy as np
import time
from fuzzywuzzy import fuzz

In [2]:
path = "./Data/withFIGI.csv"

df = pd.read_csv(path)  
df

/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (0,1,2,3,5,6,8,9,10,11,12,13,14) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD,previousCloseDate-EOD,country-Inv,...,longName-FIGI,symbol-FIGI,figi,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI
0,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02,united states,...,2U INC,TWOU,BBG001KS9450,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock
1,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03,united kingdom,...,88 ENERGY LTD,POQ,BBG000BWTTK9,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock
2,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2064.000,2022-08-03,japan,...,BIRDMAN INC,7063,BBG00NG9S234,BBG00NG9S234,BBG00NG9S261,JP,Equity,7063,Common Stock,Common Stock
3,2018,Hong Kong,HKD,HK,KYG2953R1149,AAC Technologies Holdings Inc,Common Stock,14.580,2022-08-03,hong kong,...,AAC TECHNOLOGIES HOLDINGS IN,A2XN,BBG000C162Q4,BBG000C162Q4,BBG001SKMWN2,GR,Equity,A2XN,Common Stock,Common Stock
4,2686,Hong Kong,HKD,HK,KYG000371040,AAG Energy Holdings Ltd,Common Stock,1.410,2022-08-03,hong kong,...,AAG ENERGY HOLDINGS LTD,2686,BBG009CXGZ63,BBG009CXGZ45,BBG009CXGZ54,HK,Equity,2686,Common Stock,Common Stock
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17506,NaN,NaN,NaN,NaN,US98979J1097,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17507,NaN,NaN,NaN,NaN,CA98977K1084,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17508,NaN,NaN,NaN,NaN,CA98977R1038,NaN,NaN,NaN,NaN,NaN,...,ZOOMMED INC,ZMD/H,BBG000BYKYT4,BBG000BYKYT4,BBG001SJS399,CN,Equity,ZMD/H,Common Stock,Common Stock
17509,NaN,NaN,NaN,NaN,GB00BMHTHT14,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17510,NaN,NaN,NaN,NaN,US98986T1088,NaN,NaN,NaN,NaN,NaN,...,ZYNGA INC - CL A,ZNGAEUR,BBG005YZL376,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock

## EOD vs 19.7k

In [10]:

df_Name = df[['ISIN', 'Name_197', 'Name-EOD']].dropna(subset=['Name_197'])
df_Name = df_Name[['ISIN', 'Name_197', 'Name-EOD']].dropna(subset=['Name-EOD'])

print(len(df_Name))

allD = []

for index, row in df_Name.iterrows():
    # calculate nlp scores
    fuzz_socre1 = fuzz.token_sort_ratio(row['Name_197'],row['Name-EOD'])
            
    row['fuzz_socre1'] = fuzz_socre1
    allD.append(row)
       

    if index % (len(df_Name)//10) == 0:
        print("progress: %.2f" % (100*index/len(df_Name)) + "%")

df_match = pd.DataFrame(allD).drop_duplicates(subset=['ISIN'])

df_matchFinal = df_match[df_match['fuzz_socre1']<60]
df_matchFinal.to_csv('./Data/eod-197.csv', index=False)
df_matchFinal

13016
progress: 0.00%
progress: 10.00%
progress: 19.99%
progress: 29.99%
progress: 39.98%
progress: 49.98%
progress: 59.97%
progress: 69.97%
progress: 79.96%
progress: 89.96%
progress: 99.95%

,ISIN,Name_197,Name-EOD,fuzz_socre1
38,JP3108120001,ACRODEA INC,Why How Do Co Inc,50
53,LU1250154413,ADO PROPERTIES SA,Adler Group SA,58
78,US0077371096,AEROCENTURY CORP,Mega Matrix Corp,25
165,US0185811082,ALLIANCE DATA SYSTEMS CORP,Bread Financial Holdings Inc,26
223,US0259321042,AMERICAN FINANCIAL GROUP INC,Aquatic Foods Group plc,51
...,...,...,...,...
12934,US98585L1008,YIREN DIGITAL LTD - SPS ADR,Yirendai Ltd,49
12942,CNE100002W92,YOUON TECHNOLOGY CO LTD-A,Changzhou Youon Pubilic Bicycle System Co Ltd,49
12970,CH0276534614,ZEHNDER GROUP AG-RG,Zehnder,54
12996,CNE000000FL2,ZHONGTIAN FINANCIAL GROUP -A,Zhongtian Urban Development Group Co Ltd,54
13024,HU0000074844,ZWACK UNICUM RT,Zwack Unicum Likoripari es Kereskedelmi Nyrt.,51

## Investing.com vs 19.7k

In [11]:
df_Name = df[['ISIN', 'Name_197', 'full_name-Inv']].dropna(subset=['Name_197'])
df_Name = df_Name[['ISIN', 'Name_197', 'full_name-Inv']].dropna(subset=['full_name-Inv'])

print(len(df_Name))

allD = []

for index, row in df_Name.iterrows():
    # calculate nlp scores
    fuzz_socre1 = fuzz.token_sort_ratio(row['Name_197'],row['full_name-Inv'])
            
    row['fuzz_socre1'] = fuzz_socre1
    allD.append(row)
       

    if index % (len(df_Name)//10) == 0:
        print("progress: %.2f" % (100*index/len(df_Name)) + "%")

df_match = pd.DataFrame(allD).drop_duplicates(subset=['ISIN'])

df_matchFinal = df_match[df_match['fuzz_socre1']<60]
df_matchFinal.to_csv('./Data/inv-197.csv', index=False)
df_matchFinal

6141
progress: 0.00%
progress: 10.00%
progress: 20.00%
progress: 30.00%
progress: 39.99%
progress: 49.99%
progress: 59.99%
progress: 69.99%
progress: 79.99%
progress: 219.96%

,ISIN,Name_197,full_name-Inv,fuzz_socre1
246,IL0010806136,ANALYST I.M.S.,Analyst IMS Investment Management Services Ltd,44
562,RU000A0HL5M1,BELUGA,Beluga Group PAO,55
2779,US5006432000,KORN FERRY,Korn/Ferry International,59
2965,IL0004730177,LUZON GROUP,Amos Luzon Development and Energy Group Ltd,41
3794,PLPKO0000016,PKO BANK POLSKI SA,Powszechna Kasa Oszczednosci Bank Polski SA,56
4167,FR0006239109,SCBSM,Soc Centrale Bois Scieries Manche SA,15

## IB vs 19.7k

In [12]:
df_Name = df[['ISIN', 'Name_197', 'longName-IB']].dropna(subset=['Name_197'])
df_Name = df_Name[['ISIN', 'Name_197', 'longName-IB']].dropna(subset=['longName-IB'])

print(len(df_Name))

allD = []

for index, row in df_Name.iterrows():
    # calculate nlp scores
    fuzz_socre1 = fuzz.token_sort_ratio(row['Name_197'],row['longName-IB'])
            
    row['fuzz_socre1'] = fuzz_socre1
    allD.append(row)
       

    if index % (len(df_Name)//10) == 0:
        print("progress: %.2f" % (100*index/len(df_Name)) + "%")

df_match = pd.DataFrame(allD).drop_duplicates(subset=['ISIN'])

df_matchFinal = df_match[df_match['fuzz_socre1']<60]
df_matchFinal.to_csv('./Data/ib-197.csv', index=False)
df_matchFinal

16912
progress: 0.00%
progress: 10.00%
progress: 20.00%
progress: 30.00%
progress: 40.00%
progress: 49.99%
progress: 59.99%
progress: 69.99%
progress: 89.99%
progress: 99.99%

Empty DataFrame
Columns: [ISIN, Name_197, longName-IB, fuzz_socre1]
Index: []

## FIGI vs 19.7k

In [13]:
df_Name = df[['ISIN', 'Name_197', 'longName-FIGI']].dropna(subset=['Name_197'])
df_Name = df_Name[['ISIN', 'Name_197', 'longName-FIGI']].dropna(subset=['longName-FIGI'])

print(len(df_Name))

allD = []

for index, row in df_Name.iterrows():
    # calculate nlp scores
    fuzz_socre1 = fuzz.token_sort_ratio(row['Name_197'],row['longName-FIGI'])
            
    row['fuzz_socre1'] = fuzz_socre1
    allD.append(row)
       

    if index % (len(df_Name)//10) == 0:
        print("progress: %.2f" % (100*index/len(df_Name)) + "%")

df_match = pd.DataFrame(allD).drop_duplicates(subset=['ISIN'])
df_matchFinal = df_match[df_match['fuzz_socre1']<60]
df_matchFinal.to_csv('./Data/figi-197.csv', index=False)
df_matchFinal

15485
progress: 0.00%
progress: 10.00%
progress: 19.99%
progress: 29.99%
progress: 39.99%
progress: 49.98%
progress: 59.98%
progress: 69.98%
progress: 79.97%
progress: 99.97%

,ISIN,Name_197,longName-FIGI,fuzz_socre1
2,JP3160590000,A DOT CO LTD,BIRDMAN INC,26
38,JP3108120001,ACRODEA INC,THE WHY HOW DO COMPANY INC,32
53,LU1250154413,ADO PROPERTIES SA,ADLER GROUP SA,58
78,US0077371096,AEROCENTURY CORP,MEGA MATRIX CORP,25
121,JP3102000001,AISIN SEIKI CO LTD,AISIN CORP,57
...,...,...,...,...
16577,US74838C1062,QUIKSILVER INC,BOARDRIDERS INC,21
16581,US7472623013,QVC INC 6 3/8 09/13/67 PFD,QVC INC,42
16690,SE0010520155,ROLLING OPTICS HOLDING AB,ICTA AB,31
17055,US7847882005,"SYNTHETIC FIXED-INCOME SEC STRATS 2004-2, 6.50...",STRATS-FON-04-2,36
17103,MHY8564M1057,TEEKAY LNG PARTNERS LP,SEAPEAK LLC,30

## Merge after manually check

In [56]:
path = "./Data/withFIGI.csv"

df_figiCk = pd.read_csv("./Data/figi-197.csv")
df_ibCk = pd.read_csv("./Data/ib-197.csv") 
df_eodCk = pd.read_csv("./Data/eod-197.csv") 
df_invCk = pd.read_csv("./Data/inv-197.csv")

In [57]:
df_ck = pd.merge(df_figiCk, df_ibCk, how='outer', on=['ISIN', 'Name_197'])
df_ck = pd.merge(df_ck, df_eodCk, how='outer', on=['ISIN', 'Name_197'])
df_ck = pd.merge(df_ck, df_invCk, how='outer', on=['ISIN', 'Name_197'])

df_ck = df_ck[['ISIN', 'Name_197', 'longName-FIGI', 'check-FIGI', 'longName-IB', 'check-IB', 'Name-EOD', 'check-EOD', 'full_name-Inv', 'Check-Inv']]

df_ck

,ISIN,Name_197,longName-FIGI,check-FIGI,longName-IB,check-IB,Name-EOD,check-EOD,full_name-Inv,Check-Inv
0,JP3160590000,A DOT CO LTD,BIRDMAN INC,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,JP3108120001,ACRODEA INC,THE WHY HOW DO COMPANY INC,0.0,NaN,NaN,Why How Do Co Inc,0.0,NaN,NaN
2,LU1250154413,ADO PROPERTIES SA,ADLER GROUP SA,0.0,NaN,NaN,Adler Group SA,0.0,NaN,NaN
3,US0077371096,AEROCENTURY CORP,MEGA MATRIX CORP,0.0,NaN,NaN,Mega Matrix Corp,0.0,NaN,NaN
4,JP3102000001,AISIN SEIKI CO LTD,AISIN CORP,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
405,CNE100002W92,YOUON TECHNOLOGY CO LTD-A,NaN,NaN,NaN,NaN,Changzhou Youon Pubilic Bicycle System Co Ltd,1.0,NaN,NaN
406,CH0276534614,ZEHNDER GROUP AG-RG,NaN,NaN,NaN,NaN,Zehnder,1.0,NaN,NaN
407,CNE000000FL2,ZHONGTIAN FINANCIAL GROUP -A,NaN,NaN,NaN,NaN,Zhongtian Urban Development Group Co Ltd,1.0,NaN,NaN
408,HU0000074844,ZWACK UNICUM RT,NaN,NaN,NaN,NaN,Zwack Unicum Likoripari es Kereskedelmi Nyrt.,1.0,NaN,NaN
409,US5006432000,KORN FERRY,NaN,NaN,NaN,NaN,NaN,NaN,Korn/Ferry International,1.0

In [58]:
df_ck['Not_Match'] = ""

df_ck.loc[df_ck['check-FIGI']==0,'Not_Match'] = 'FIGI;'
df_ck.loc[df_ck['check-IB']==0,'Not_Match'] = 'IB;' + df_ck['Not_Match'].astype(str)
df_ck.loc[df_ck['check-EOD']==0,'Not_Match'] = 'EOD;' + df_ck['Not_Match'].astype(str)
df_ck.loc[df_ck['Check-Inv']==0,'Not_Match'] = 'Inv;' + df_ck['Not_Match'].astype(str)

df_ck['Not_Match'] = df_ck['Not_Match'].replace('', np.nan)

df_ck

,ISIN,Name_197,longName-FIGI,check-FIGI,longName-IB,check-IB,Name-EOD,check-EOD,full_name-Inv,Check-Inv,Not_Match
0,JP3160590000,A DOT CO LTD,BIRDMAN INC,0.0,NaN,NaN,NaN,NaN,NaN,NaN,FIGI;
1,JP3108120001,ACRODEA INC,THE WHY HOW DO COMPANY INC,0.0,NaN,NaN,Why How Do Co Inc,0.0,NaN,NaN,EOD;FIGI;
2,LU1250154413,ADO PROPERTIES SA,ADLER GROUP SA,0.0,NaN,NaN,Adler Group SA,0.0,NaN,NaN,EOD;FIGI;
3,US0077371096,AEROCENTURY CORP,MEGA MATRIX CORP,0.0,NaN,NaN,Mega Matrix Corp,0.0,NaN,NaN,EOD;FIGI;
4,JP3102000001,AISIN SEIKI CO LTD,AISIN CORP,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
405,CNE100002W92,YOUON TECHNOLOGY CO LTD-A,NaN,NaN,NaN,NaN,Changzhou Youon Pubilic Bicycle System Co Ltd,1.0,NaN,NaN,NaN
406,CH0276534614,ZEHNDER GROUP AG-RG,NaN,NaN,NaN,NaN,Zehnder,1.0,NaN,NaN,NaN
407,CNE000000FL2,ZHONGTIAN FINANCIAL GROUP -A,NaN,NaN,NaN,NaN,Zhongtian Urban Development Group Co Ltd,1.0,NaN,NaN,NaN
408,HU0000074844,ZWACK UNICUM RT,NaN,NaN,NaN,NaN,Zwack Unicum Likoripari es Kereskedelmi Nyrt.,1.0,NaN,NaN,NaN
409,US5006432000,KORN FERRY,NaN,NaN,NaN,NaN,NaN,NaN,Korn/Ferry International,1.0,NaN

In [59]:
df_matchFinal = df_ck[df_ck['Not_Match']!='']
df_matchFinal

,ISIN,Name_197,longName-FIGI,check-FIGI,longName-IB,check-IB,Name-EOD,check-EOD,full_name-Inv,Check-Inv,Not_Match
0,JP3160590000,A DOT CO LTD,BIRDMAN INC,0.0,NaN,NaN,NaN,NaN,NaN,NaN,FIGI;
1,JP3108120001,ACRODEA INC,THE WHY HOW DO COMPANY INC,0.0,NaN,NaN,Why How Do Co Inc,0.0,NaN,NaN,EOD;FIGI;
2,LU1250154413,ADO PROPERTIES SA,ADLER GROUP SA,0.0,NaN,NaN,Adler Group SA,0.0,NaN,NaN,EOD;FIGI;
3,US0077371096,AEROCENTURY CORP,MEGA MATRIX CORP,0.0,NaN,NaN,Mega Matrix Corp,0.0,NaN,NaN,EOD;FIGI;
4,JP3102000001,AISIN SEIKI CO LTD,AISIN CORP,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
405,CNE100002W92,YOUON TECHNOLOGY CO LTD-A,NaN,NaN,NaN,NaN,Changzhou Youon Pubilic Bicycle System Co Ltd,1.0,NaN,NaN,NaN
406,CH0276534614,ZEHNDER GROUP AG-RG,NaN,NaN,NaN,NaN,Zehnder,1.0,NaN,NaN,NaN
407,CNE000000FL2,ZHONGTIAN FINANCIAL GROUP -A,NaN,NaN,NaN,NaN,Zhongtian Urban Development Group Co Ltd,1.0,NaN,NaN,NaN
408,HU0000074844,ZWACK UNICUM RT,NaN,NaN,NaN,NaN,Zwack Unicum Likoripari es Kereskedelmi Nyrt.,1.0,NaN,NaN,NaN
409,US5006432000,KORN FERRY,NaN,NaN,NaN,NaN,NaN,NaN,Korn/Ferry International,1.0,NaN

In [62]:
df = pd.merge(df, df_matchFinal[['ISIN','Not_Match']], how='outer', on='ISIN')

df

,Code-EOD,Country-EOD,Currency-EOD,Exchange-EOD,ISIN,Name-EOD,Type-EOD,previousClose-EOD,previousCloseDate-EOD,country-Inv,...,compositeFIGI,shareClassFIGI,exchCode-FIGI,marketSector-FIGI,securityDescription-FIGI,securityType-FIGI,securityType2-FIGI,Not_Match_x,Not_Match_y,Not_Match
0,TWOU,USA,USD,US,US90214J1016,2U Inc,Common Stock,9.200,2022-08-02,united states,...,BBG001KS9450,BBG001V0RR30,US,Equity,TWOU,Common Stock,Common Stock,NaN,NaN,NaN
1,88E,UK,GBX,LSE,AU00000088E2,88 Energy Ltd,Common Stock,0.625,2022-08-03,united kingdom,...,BBG000BWTTK9,BBG001SCV1F7,GR,Equity,POQ,Common Stock,Common Stock,NaN,NaN,NaN
2,7063,Japan,JPY,TSE,JP3160590000,A Dot Co Ltd,Common Stock,2064.000,2022-08-03,japan,...,BBG00NG9S234,BBG00NG9S261,JP,Equity,7063,Common Stock,Common Stock,FIGI;,FIGI;,FIGI;
3,2018,Hong Kong,HKD,HK,KYG2953R1149,AAC Technologies Holdings Inc,Common Stock,14.580,2022-08-03,hong kong,...,BBG000C162Q4,BBG001SKMWN2,GR,Equity,A2XN,Common Stock,Common Stock,NaN,NaN,NaN
4,2686,Hong Kong,HKD,HK,KYG000371040,AAG Energy Holdings Ltd,Common Stock,1.410,2022-08-03,hong kong,...,BBG009CXGZ45,BBG009CXGZ54,HK,Equity,2686,Common Stock,Common Stock,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17506,NaN,NaN,NaN,NaN,US98979J1097,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17507,NaN,NaN,NaN,NaN,CA98977K1084,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17508,NaN,NaN,NaN,NaN,CA98977R1038,NaN,NaN,NaN,NaN,NaN,...,BBG000BYKYT4,BBG001SJS399,CN,Equity,ZMD/H,Common Stock,Common Stock,NaN,NaN,NaN
17509,NaN,NaN,NaN,NaN,GB00BMHTHT14,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17510,NaN,NaN,NaN,NaN,US98986T1088,NaN,NaN,NaN,NaN,NaN,...,BBG005YZL2R6,BBG001T24RN2,XS,Equity,ZNGAEUR,Common Stock,Common Stock,NaN,NaN,NaN

In [49]:
df.to_csv('./Data/withFIGI.csv')

In [64]:
df_notMatch = df[df['Not_Match']=='EOD;FIGI;']
df_notMatch = df_notMatch[['ISIN', 'Name-EOD', 'longName-FIGI']]

df_notMatch

,ISIN,Name-EOD,longName-FIGI
38,JP3108120001,Why How Do Co Inc,THE WHY HOW DO COMPANY INC
53,LU1250154413,Adler Group SA,ADLER GROUP SA
78,US0077371096,Mega Matrix Corp,MEGA MATRIX CORP
165,US0185811082,Bread Financial Holdings Inc,BREAD FINANCIAL HOLDINGS INC
484,JP3160770008,Wow World Inc,WOW WORLD INC
491,IL0011016669,Abra Information Technologies Ltd,ABRA INFORMATION TECHNOLOGIE
574,CNE0000005N4,New Guomai Digital Culture Co Ltd,NEW GUOMAI DIGITAL CULTURE-A
595,US09074B1070,Renovare Environmental Inc,RENOVARE ENVIRONMENTAL INC
696,US1143401024,Azenta Inc,AZENTA INC
736,US1270971039,Coterra Energy Inc,COTERRA ENERGY INC
1008,IL0004560129,Upsellon Brands Holdings Ltd,UPSELLON BRANDS HOLDINGS LTD
1197,JP3236100008,Small and medium Sized Enterprises Holdings Inc,SMALL AND MEDIUM SIZED ENTER
1227,US2289031005,Artivion Inc,ARTIVION INC
1312,GB00B1722W11,Jet2 PLC,JET2 PLC
1496,GB0003085445,Unbound Group PLC,UNBOUND GROUP PLC
1899,JP3386460004,Kidswell Bio Corporation,KIDSWELL BIO CORP
2051,GB00BYRH4982,Rockwood Realisation PLC,ROCKWOOD STRATEGIC PLC
2054,FR0011038348,Klarsen SA,KLARSEN
2083,IM00B5VQMV65,Entain PLC,ENTAIN PLC
2332,JP3142450000,Bruno Inc,BRUNO INC
2510,US48123V1026,Ziff Davis Inc,ZIFF DAVIS INC
2560,JP3385950005,Delsole Corp,DELSOLE CORP
2667,JP3226700007,OLBA Healthcare Holdings Inc,OLBA HEALTHCARE HOLDINGS INC
2848,US5207761058,Distribution Solutions Group Inc,DISTRIBUTION SOLUTIONS GROUP
2862,JP3980300002,CL Holdings Inc,CL HOLDINGS INC
2876,US5290431015,LXP Industrial Trust,LXP INDUSTRIAL TRUST
2894,US53261M1045,Edgio Inc,EDGIO INC
3104,IL0010826191,Sharplink Gaming Ltd,SHARPLINK GAMING LTD
3410,JP3754200008,Biprogy Inc,BIPROGY INC
3682,JP3781520006,Success Holders Inc,SUCCESS HOLDERS INC
3707,JP3780150003,Tameny Inc,TAMENY INC
3943,US75605Y1064,Anywhere Real Estate Inc,ANYWHERE REAL ESTATE INC
4061,GB00B7T77214,NatWest Group PLC,NATWEST GROUP PLC
4177,US80874P1093,Light & Wonder Inc,LIGHT & WONDER INC
4194,JP3347010005,Meldia Development & Construction CO LTD,MELDIA DEVELOPMENT & CONSTRU
4245,CNE000000C17,DLG Exhibitions & Events Corp Ltd,DLG EXHIBITIONS & EVENTS C-A
4257,IL0003410169,Nala Digital Commerce Ltd,NALA DIGITAL COMMERCE LTD
4281,JP3373200009,Kobelco Wire Co Ltd,KOBELCO WIRE CO LTD
4402,GB00BF1BK408,Scirocco Energy PLC,SCIROCCO ENERGY PLC
4408,VGG826421023,Nostromo Energy Ltd,NOSTROMO ENERGY LTD
4496,GB00B4X3Q493,Afentra PLC,AFENTRA PLC
4499,GB00B03HDJ73,Esken Ltd,ESKEN LTD
4544,KYG857AT1018,Imperium Financial Group Ltd,IMPERIUM FINANCIAL GROUP LTD
4573,JP3397150008,Food & Life Companies Ltd,FOOD & LIFE COMPANIES LTD
5153,CNE000000024,Wushang Group Co Ltd,WUSHANG GROUP CO LTD-A
6830,US1255258576,Creative Media & Community Trust Corporation P...,CREATIVE MEDIA & CMNTY
7070,US74913G8731,Qwest Corp 6 75 Notes Expiry 2057,QWEST CORP
11591,DE000A0DPRE6,Allane SE,ALLANE SE
11847,US22532R1014,Credit Enhanced Corts Trust For Aon Capital A GIC,CORTS TRUST FOR AON CAP
12735,US94770G1058,Veridetx Corp,ONEMETA AI

In [55]:
df_Name = df_notMatch.copy()

print(len(df_Name))

allD = []

for index, row in df_Name.iterrows():
    # calculate nlp scores
    fuzz_socre1 = fuzz.token_sort_ratio(row['Name-EOD'],row['longName-FIGI'])
            
    row['fuzz_socre1'] = fuzz_socre1
    allD.append(row)
       

    if index % (len(df_Name)//10) == 0:
        print("progress: %.2f" % (100*index/len(df_Name)) + "%")

df_match = pd.DataFrame(allD).drop_duplicates(subset=['ISIN'])
df_match[df_match['fuzz_socre1']<60]

50
progress: 330.00%
progress: 1190.00%
progress: 5020.00%
progress: 5120.00%
progress: 6820.00%
progress: 8490.00%
progress: 13660.00%
progress: 14140.00%
progress: 25470.00%

,ISIN,Name-EOD,longName-FIGI,fuzz_socre1
2051,GB00BYRH4982,Rockwood Realisation PLC,ROCKWOOD STRATEGIC PLC,52
6830,US1255258576,Creative Media & Community Trust Corporation P...,CREATIVE MEDIA & CMNTY,49
7070,US74913G8731,Qwest Corp 6 75 Notes Expiry 2057,QWEST CORP,47
12735,US94770G1058,Veridetx Corp,ONEMETA AI,35