In [1]:
import numpy as np
import pandas as pd

## Threshould

In [7]:
# read data from data souce mentioned above
df_rated = pd.read_csv('./Data/urls_2020.csv', index_col=0)

df_rated

,Unnamed: 0.1,date,Ticker,ISIN,COMPANY,GICS Sector,SDG_1,SDG_2,SDG_3,SDG_4,...,SDG_8_url,SDG_9_url,SDG_10_url,SDG_11_url,SDG_12_url,SDG_13_url,SDG_14_url,SDG_15_url,SDG_16_url,SDG_17_url
2466,2466,2020-01-01,A,US00846U1016,agilent technologies inc,Health Care,-0.589971,-0.589971,-0.589971,-0.589971,...,['https://advances.sciencemag.org/content/6/1/...,['https://advances.sciencemag.org/content/6/1/...,['https://advances.sciencemag.org/content/6/1/...,['https://advances.sciencemag.org/content/6/1/...,[],['https://advances.sciencemag.org/content/6/1/...,[],['https://advances.sciencemag.org/content/6/1/...,['https://advances.sciencemag.org/content/6/1/...,[]
2467,2467,2020-01-02,A,US00846U1016,agilent technologies inc,Health Care,NaN,NaN,-1.164272,2.448040,...,['https://mrtopstep.com/bull-of-the-day-keysig...,['https://www.nasdaq.com/articles/keysight-ana...,['https://mrtopstep.com/bull-of-the-day-keysig...,['https://www.finanzen.ch/nachrichten/aktien/a...,['https://www.nasdaq.com/articles/keysight-ana...,[],[],[],['https://mrtopstep.com/bull-of-the-day-keysig...,['https://www.finanzen.ch/nachrichten/aktien/a...
2468,2468,2020-01-03,A,US00846U1016,agilent technologies inc,Health Care,NaN,1.658375,0.450984,0.048520,...,['https://www.thedailytimes.com/business/latin...,['https://www.healthcaredive.com/news/illumina...,['https://www.healthcaredive.com/news/illumina...,['https://www.briefingwire.com/pr/food-testing...,['https://www.healthcaredive.com/news/illumina...,[],[],[],['https://www.briefingwire.com/pr/food-testing...,['https://www.biospectrumindia.com/news/60/154...
2469,2469,2020-01-04,A,US00846U1016,agilent technologies inc,Health Care,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2470,2470,2020-01-05,A,US00846U1016,agilent technologies inc,Health Care,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631131,1631131,2020-05-23,ZTS,US98978V1035,zoetis inc,Health Care,NaN,3.271895,3.271895,NaN,...,[],[],[],['https://www.marketscreener.com/news/Research...,[],[],[],[],['https://www.marketscreener.com/news/Research...,['https://www.marketscreener.com/news/Research...
1631132,1631132,2020-05-24,ZTS,US98978V1035,zoetis inc,Health Care,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1631133,1631133,2020-05-25,ZTS,US98978V1035,zoetis inc,Health Care,NaN,NaN,1.264517,NaN,...,[],[],[],['http://baytownsun.com/coronavirus/article_9e...,[],[],[],[],['http://baytownsun.com/coronavirus/article_9e...,['http://baytownsun.com/coronavirus/article_9e...
1631134,1631134,2020-05-26,ZTS,US98978V1035,zoetis inc,Health Care,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1631135,1631135,2020-05-27,ZTS,US98978V1035,zoetis inc,Health Care,1.521298,1.521298,-1.987826,-3.157534,...,['https://www.insidermonkey.com/blog/hedge-fun...,['https://www.msn.com/en-au/health/medical/ant...,['https://www.insidermonkey.com/blog/hedge-fun...,['https://www.newyorktelegraph.com/news/265234...,[],[],['https://www.msn.com/en-au/health/medical/ant...,[],['https://www.newyorktelegraph.com/news/265234...,[]

In [10]:
# calculate daily difference
df_diff = df_rated[['MA_7day_1', 'MA_7day_2', 'MA_7day_3', 'MA_7day_4', 'MA_7day_5', 'MA_7day_6', 'MA_7day_7', 'MA_7day_8', 'MA_7day_9', 'MA_7day_10', 'MA_7day_11', 'MA_7day_12', 'MA_7day_13', 'MA_7day_14', 'MA_7day_15', 'MA_7day_16', 'MA_7day_17', 'MA_7day_Mean']].diff()
columns_lst = ['diff_'+str(i) for i in range(1,18)]
columns_lst.append('diff_Mean')
df_diff.columns = columns_lst
df_merge = pd.concat([df_rated,df_diff],axis=1)
first = min(df_merge['date'])
indexer = df_merge[df_merge['date']== first].index
df_merge.loc[indexer, columns_lst]= float("NAN")

df_diff

,diff_1,diff_2,diff_3,diff_4,diff_5,diff_6,diff_7,diff_8,diff_9,diff_10,diff_11,diff_12,diff_13,diff_14,diff_15,diff_16,diff_17,diff_Mean
2466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2467,0.000000,0.000000,-0.199760,0.312375,0.0,0.0,0.0,0.111285,-0.024965,0.298250,-0.098959,-0.396362,0.0,0.000000,0.0,0.340291,1.036085,0.116935
2468,0.000000,0.002758,0.130317,-0.240947,0.0,0.0,0.0,-0.300368,-0.248044,-0.219199,-0.100653,-0.731114,0.0,0.000000,0.0,0.009611,0.360068,-0.107897
2469,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
2470,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631131,0.000000,0.904149,1.029462,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,1.055332,0.000000,0.0,0.000000,0.0,1.023983,0.898150,0.408364
1631132,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
1631133,0.000000,0.000000,0.279773,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.271303,0.000000,0.0,0.000000,0.0,0.290780,0.216687,0.088969
1631134,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
1631135,0.108459,-0.151247,-0.504099,-0.478690,0.0,0.0,0.0,-0.363593,-1.923518,0.081880,-0.475545,0.000000,0.0,-1.794455,0.0,-0.512242,0.000000,-0.509801

In [11]:
df_merge

,Unnamed: 0.1,date,Ticker,ISIN,COMPANY,GICS Sector,SDG_1,SDG_2,SDG_3,SDG_4,...,diff_9,diff_10,diff_11,diff_12,diff_13,diff_14,diff_15,diff_16,diff_17,diff_Mean
2466,2466,2020-01-01,A,US00846U1016,agilent technologies inc,Health Care,-0.589971,-0.589971,-0.589971,-0.589971,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2467,2467,2020-01-02,A,US00846U1016,agilent technologies inc,Health Care,NaN,NaN,-1.164272,2.448040,...,-0.024965,0.298250,-0.098959,-0.396362,0.0,0.000000,0.0,0.340291,1.036085,0.116935
2468,2468,2020-01-03,A,US00846U1016,agilent technologies inc,Health Care,NaN,1.658375,0.450984,0.048520,...,-0.248044,-0.219199,-0.100653,-0.731114,0.0,0.000000,0.0,0.009611,0.360068,-0.107897
2469,2469,2020-01-04,A,US00846U1016,agilent technologies inc,Health Care,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
2470,2470,2020-01-05,A,US00846U1016,agilent technologies inc,Health Care,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1631131,1631131,2020-05-23,ZTS,US98978V1035,zoetis inc,Health Care,NaN,3.271895,3.271895,NaN,...,0.000000,0.000000,1.055332,0.000000,0.0,0.000000,0.0,1.023983,0.898150,0.408364
1631132,1631132,2020-05-24,ZTS,US98978V1035,zoetis inc,Health Care,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
1631133,1631133,2020-05-25,ZTS,US98978V1035,zoetis inc,Health Care,NaN,NaN,1.264517,NaN,...,0.000000,0.000000,0.271303,0.000000,0.0,0.000000,0.0,0.290780,0.216687,0.088969
1631134,1631134,2020-05-26,ZTS,US98978V1035,zoetis inc,Health Care,NaN,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000
1631135,1631135,2020-05-27,ZTS,US98978V1035,zoetis inc,Health Care,1.521298,1.521298,-1.987826,-3.157534,...,-1.923518,0.081880,-0.475545,0.000000,0.0,-1.794455,0.0,-0.512242,0.000000,-0.509801

In [12]:
# create a thresh table
col = ["freq", "count", "std", "level", "change"]
for i in range(1,18):
    col.append('SDG_'+str(i)+'_count')
    col.append('SDG_'+str(i)+'_std')
thresh = pd.DataFrame(columns=col)
day = {"freq":"day", "count":0.5, "std":0.5, "level":1.3, "change":0.8}
week = {"freq":"week", "count":0.5, "std":0.5, "level":2.3, "change":1.15}
month = {"freq":"month", "count":0.5, "std":0.5, "level":2.20, "change":1.75}
thresh = thresh.append(day, ignore_index=True)
thresh = thresh.append(week, ignore_index=True)
thresh = thresh.append(month, ignore_index=True)

# populate counts and std
for i in range(3):
    for sdg in range(1,18):
        thresh['SDG_'+str(sdg)+'_count'] = df_merge['SDG_'+str(sdg)+'_count'].quantile([thresh['count'][i]]).values[0]
        thresh['SDG_'+str(sdg)+'_std'] = df_merge['SDG_'+str(sdg)+'_std'].quantile([thresh['std'][i]]).values[0]
        
thresh

,freq,count,std,level,change,SDG_1_count,SDG_1_std,SDG_2_count,SDG_2_std,SDG_3_count,...,SDG_13_count,SDG_13_std,SDG_14_count,SDG_14_std,SDG_15_count,SDG_15_std,SDG_16_count,SDG_16_std,SDG_17_count,SDG_17_std
0,day,0.5,0.5,1.3,0.80,2.0,2.0,2.0,2.0,4.0,...,2.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0
1,week,0.5,0.5,2.3,1.15,2.0,2.0,2.0,2.0,4.0,...,2.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0
2,month,0.5,0.5,2.2,1.75,2.0,2.0,2.0,2.0,4.0,...,2.0,2.0,2.0,2.0,2.0,2.0,4.0,2.0,2.0,2.0